version: '3.1'
services:
  mongo:
    image: mongo
    ports:
    - 28017:27017
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db1
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
            - 29017:27017
    command: mongod --smallfiles --logpath=/dev/null

